# This file is used to configure the Render service for the Flask ML API.
services:
  - type: web
    name: flask-ml-api
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
